openapi: 3.0.0
info:
  description: X-Road Central Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
  version: "1.0.0"
  title: X-Road Central Server Admin API
  contact:
    name: Nordic Institute for Interoperability Solutions (NIIS)
    url: https://github.com/nordic-institute/X-Road-development/#enhancement-requests-and-error-reports
    email: info@niis.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api/v1
    description: basepath for API v1
paths:
  /system/version:
    get:
      tags:
        - system
      summary: get information for the system version
      operationId: systemVersion
      responses:
        '200':
          description: system version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
        '400':
          description: request was invalid
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '500':
          description: internal server error
  /system/status:
    get:
      tags:
        - system
      summary: get the system status
      operationId: systemStatus
      responses:
        '200':
          description: system status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatus'
        '400':
          description: request was invalid
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '500':
          description: internal server error
  /system/high-availability-status:
    get:
      tags:
        - system
      summary: get the system high availability status
      operationId: highAvailabilityStatus
      responses:
        '200':
          description: system high availability status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HighAvailabilityStatus'
        '400':
          description: request was invalid
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '500':
          description: internal server error
  /system/instance-identifier:
    get:
      tags:
        - system
      summary: get the instance identifier
      operationId: instanceidentifier
      responses:
        '200':
          description: instance identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceIdentifier'
        '400':
          description: request was invalid
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '500':
          description: internal server error
  /system/central-server-address:
    get:
      tags:
        - system
      summary: get the central server address
      operationId: centralServerAddress
      responses:
        '200':
          description: central server address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralServerAddress'
        '400':
          description: request was invalid
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '500':
          description: internal server error
  /initialization:
    post:
      tags:
        - initialization
      summary: Initialize a new central server with the provided initial configuration
      operationId: initCentralServer
      description:
        <h3>Administrator initializes a new Central Server with the provided initial configuration.</h3>
        <p>
        This endpoint can also return metadata in the error response. The metadata array can contain error messages about why the init did not succeed.
        If the pin code is too weak, the error code <code>weak_pin</code> is used and the entries in the metadata array are always ordered in following way
        <ul>
        <li>metadata has a list of strings ["pin_min_length", x, "pin_min_char_classes_count", y] where</li>
        <li>x = the minimum length of the pin code</li>
        <li>y = the minimum amount of character classes (e.g. uppercase, number, special characters) to be used in the pin code</li>
        </ul>
        Other possible error code are
        <ul>
        <li><code>invalid_init_params</code> for "business" logic problems which can have any one or more of the following strings in the metadata field.
        There "_exists" -entries are returned if parameter has been given already in partially succeeded initialization.
        The "_not_provided"-entries are returned if these parameters is needed still for the initialization,  but it is not given in the request.

        </li>


        <ul>
        <li>pin_code_exists</li>
        <li>pin_code_not_provided</li>
        <li>server_address_exists</li>
        <li>server_address_not_provided</li>
        <li>instance_identifier_exists</li>
        <li>instance_identifier_not_provided</li>
        </ul>
        <li><code>validation_failure</code> for parameter format errors
        </ul>
        </p>
        </p>
        <strong>See the '400' response examples</strong>
      requestBody:
        description: initial central server configuration
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitialServerConf'
      responses:
        '201':
          description: central server initialized
        '400':
          description: request was invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              examples:
                error_response:
                  $ref: '#/components/examples/ErrorExample'
                error_invalid_init_params:
                  $ref: '#/components/examples/ErrorInvalidInitParamsMetadataExample'
                error_weak_pin:
                  $ref: '#/components/examples/ErrorWeakPinMetadataExample'
                warnings_response:
                  $ref: '#/components/examples/InitializationWarningExample'
                validation_errors_response:
                  $ref: '#/components/examples/ValidationErrorsExample'
        '401':
          description: authentication credentials are missing
        '403':
          description: request has been refused
        '404':
          description: resource requested does not exists
        '406':
          description: request specified an invalid format
        '409':
          description: an existing item already exists
        '500':
          description: internal server error
  /initialization/status:
      get:
        tags:
          - initialization
        summary: Check the initialization status of the Central Server
        operationId: getInitializationStatus
        description: <h3>Administrator checks the initialization status of the Central Server.</h3>
        responses:
          '200':
            description: initialization status of the Central Server
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/InitializationStatus'
          '400':
            description: request was invalid
          '401':
            description: authentication credentials are missing
          '403':
            description: request has been refused
          '404':
            description: resource requested does not exists
          '406':
            description: request specified an invalid format
          '409':
            description: an existing item already exists
          '500':
            description: internal server error
components:
  schemas:
    InitializationStatus:
      type: object
      description: Initialization status of the Central Server
      required:
        - instance_identifier
        - central_server_address
        - software_token_init_status
      properties:
        instance_identifier:
          $ref: '#/components/schemas/InstanceIdentifier'
        central_server_address:
          $ref: '#/components/schemas/CentralServerAddress'
        software_token_init_status:
          $ref: '#/components/schemas/TokenInitStatus'
    InitialServerConf:
      type: object
      description: central server initial configuration
      properties:
        instance_identifier:
          $ref: '#/components/schemas/InstanceIdentifier'
        central_server_address:
          $ref: '#/components/schemas/CentralServerAddress'
        software_token_pin:
          type: string
          format: text
          description: pin code for the initial software token
          example: sup3rs3cr3t_p!n
          minLength: 1
          maxLength: 255
    TokenInitStatus:
      type: string
      format: enum
      description: whether a token has been initialized or not – if the software token init status
        cannot be resolved (e.g. signer module is offline), the value is UNKNOWN
      example: INITIALIZED
      enum:
        - INITIALIZED
        - NOT_INITIALIZED
        - UNKNOWN
    InstanceIdentifier:
      type: string
      format: text
      description: Valid instance identifier, shall not contain colon, semicolon, forwardslash, backslash, percent or control characters.
      example: FI-TEST
      minLength: 1
      maxLength: 255
    CentralServerAddress:
      type: string
      format: text
      description: Central server’s public DNS name or external IP address
    HighAvailabilityStatus:
      type: object
      description: Central server's high availability status
      properties:
        is_ha_configured:
          type: boolean
          description: indicates if the central server is in high availability mode
          default: false
        node_name:
          type: string
          format: text
          description: central server's node name
          example: node_0
          minLength: 1
          maxLength: 255
    SystemStatus:
      type: object
      description: Central server's status
      properties:
        initialization_status:
          $ref: '#/components/schemas/InitializationStatus'
        high_availability_status:
          $ref: '#/components/schemas/HighAvailabilityStatus'
    Version:
      type: object
      description: version information
      required:
        - info
      properties:
        info:
          type: string
          format: text
          description: information about the security server
          example: Security Server version 6.21.0-SNAPSHOT-20190411git32add470
          minLength: 1
          maxLength: 255
    ErrorInfo:
      $ref: '../../../../../common-rest-api/src/main/resources/common-openapi-definition.yaml#/components/schemas/ErrorInfo'
    CodeWithDetails:
      $ref: '../../../../../common-rest-api/src/main/resources/common-openapi-definition.yaml#/components/schemas/CodeWithDetails'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: X-Road-ApiKey token=<api key>
      # https://github.com/nordic-institute/X-Road-REST-UI/blob/XRDDEV-237/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#1911-creating-new-api-keys
  examples:
    ErrorExample:
      $ref: '../../../../../common-rest-api/src/main/resources/common-openapi-definition.yaml#/components/examples/ErrorExample'
    ErrorWithMetadataExample:
      $ref: '../../../../../common-rest-api/src/main/resources/common-openapi-definition.yaml#/components/examples/ErrorWithMetadataExample'
    ErrorInvalidInitParamsMetadataExample:
      summary: Initialization error with metadata
      value:
        status: 400
        error:
          code: invalid_init_params
          metadata:
            - "server_address_not_provided"
            - "instance_id_not_provided"
            - "pin_code_exists"
    ErrorWeakPinMetadataExample:
      summary: Initialization or pin change error with metadata when the provided pin is too weak
      value:
        status: 400
        error:
          code: weak_pin
          metadata:
            - "pin_min_length"
            - "8"
            - "pin_min_char_classes_count"
            - "3"
    InitializationWarningExample:
      summary: All initialization warnings example.
      value:
        status: 400
        error:
          code: warnings_detected
        warnings:
          - code: init_software_token_initialized
    ValidationErrorsExample:
      summary: Validation errors response body example
      value:
        status: 400
        error:
          code: validation_failure
          validation_errors:
            "initialServerConf.instanceIdentifier":
              - IdentifierChars
security:
  - ApiKeyAuth: []
